### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mady143** [JAIJANYANI/Automated-Resume-Screening-System#33] opened 2020-03-11 09:33 UTC
Hi @eduardosgs @jirawatp @fgriberi @paulo-filho-dev @jofftiquez ,

when i am running python app.py getting an error

**FileNotFoundError
FileNotFoundError: [Errno 2] No such file or directory: './Job_Description/pedescription.txt'**

Thanks and Regards,
Manikantha Sekhar

**Comment by stablexbt** [comment] 2020-03-14 04:59
Duplicate of #34

**Closed as completed by stablexbt** 2020-03-14 04:59 UTC

**Comment by jofftiquez** [comment] 2020-03-14 07:39
Hello @mady143 wrong tag. Hehe.
